version: "3.8"

services:
  backend:
    # container_name: "silkroad"
    build:
      context: .
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - postgres-db
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  database:
    # container_name: "postgres"
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: silkroad
    volumes:
      - dbdata:/var/lib/postgressql/data
    networks:
      - postgres-db
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
volumes:
  dbdata:
networks:
  postgres-db:
